# Use this file to create an Anaconda environment with:
# %> conda env create -f environment.yml [-n better_name]

name: argos
dependencies:
  - python >= 3.4
  - numpy
  - pyqt
  - h5py
  - netcdf4
  - pillow
  - scipy
  - pandas
  - pyqtgraph >= 0.10.0
  - conda-forge::cmlib
  - conda-forge::pgcolorbar
